=== unep-grid/mapx/app/src/js/theme/schema.json
{
  "$async": true,
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "description": {
      "type": "object",
      "properties": {
        "en": {
          "type": "string"
        }
      },
      "required": ["en"]
    },
    "mode": {
      "type": "string",
      "enum": ["light", "dark"]
    },
    "author": {
      "type": "string"
    },
    "sound": {
      "type": "string",
      "enum": ["switch-on", "switch-off"]
    },
    "colors": {
      "type": "object",
      "patternProperties": {       "^(mx_ui_text|mx_ui_link|mx_ui_input_accent|mx_ui_text_faded|mx_ui_hidden|mx_ui_border|mx_ui_background|mx_ui_background_accent|mx_ui_background_faded|mx_ui_background_contrast|mx_ui_background_transparent|mx_ui_shadow|mx_map_background|mx_map_feature_highlight|mx_map_hillshade_shadow|mx_map_hillshade_highlight|mx_map_mask|mx_map_text_place|mx_map_text_road|mx_map_text_water|mx_map_text_water_outline|mx_map_water|mx_map_bathymetry_high|mx_map_bathymetry_low|mx_map_bathymetry_lines|mx_map_road|mx_map_road_border|mx_map_building|mx_map_boundary_un_1|mx_map_boundary_un_2|mx_map_boundary_un_3|mx_map_boundary_un_4|mx_map_boundary_un_8|mx_map_boundary_un_9|mx_map_boundary_un_6|mx_map_text_land_outline|mx_map_text_bathymetry_outline|mx_map_text_bathymetry|mx_map_text_country_0_0|mx_map_text_country_0_1|mx_map_text_country_0_2|mx_map_text_country_0_3|mx_map_text_country_0_4|mx_map_text_country_0_5|mx_map_text_country_0_99|mx_map_text_country_1_1)$": {
          "type": "object",
          "properties": {
            "visibility": {
              "type": "string",
              "enum": ["visible", "none"]
            },
            "color": {
              "type": "string",
              "pattern": "^rgba?\\((\\d{1,3}),\\s?(\\d{1,3}),\\s?(\\d{1,3})(,\\s?((0(\\.\\d{1,2})?)|(1(\\.0{1,2})?)))?\\)$"
            },
            "font": {
              "type": "string"
            }
          },
          "required": ["visibility", "color"]
        }
      },
      "additionalProperties": false
    }
  },
  "required": ["id", "description", "mode", "author", "sound", "colors"]
}

=== unep-grid/mapx/app/src/js/theme/themes/ocean_light.json
{
  "id": "ocean_light",
  "description": {
    "en": "Ocean theme"
  },
  "mode": "light",
  "author": "F.Moser",
  "sound": "switch-on",
  "colors": {
    "mx_ui_text": {
      "visibility": "visible",
      "color": "rgb(53,53,53)"
    },
    "mx_ui_link": {
      "visibility": "visible",
      "color": "rgb(17,176,248)"
    },
    "mx_ui_input_accent": {
      "visibility": "visible",
      "color": "rgb(17,176,248)"
    },
    "mx_ui_text_faded": {
      "visibility": "visible",
      "color": "rgba(53,53,53,0.5)"
    },
    "mx_ui_hidden": {
      "visibility": "visible",
      "color": "rgba(2,186,253,0)"
    },
    "mx_ui_border": {
      "visibility": "visible",
      "color": "rgba(156,156,156,0.2)"
    },
    "mx_ui_background": {
      "visibility": "visible",
      "color": "rgb(255,255,255)"
    },
    "mx_ui_background_accent": {
      "visibility": "visible",
      "color": "rgb(252,252,252)"
    },
    "mx_ui_background_faded": {
      "visibility": "visible",
      "color": "rgb(250,250,250)"
    },
    "mx_ui_background_contrast": {
      "visibility": "visible",
      "color": "rgb(245,245,245)"
    },
    "mx_ui_background_transparent": {
      "visibility": "visible",
      "color": "rgba(245,245,245,0.4)"
    },
    "mx_ui_shadow": {
      "visibility": "visible",
      "color": "rgba(61,61,61,0.09)"
    },
    "mx_map_background": {
      "visibility": "visible",
      "color": "rgb(255,255,255)"
    },
    "mx_map_feature_highlight": {
      "visibility": "visible",
      "color": "rgb(255,0,255)"
    },
    "mx_map_hillshade_shadow": {
      "visibility": "visible",
      "color": "rgba(145,145,145,0.1)"
    },
    "mx_map_hillshade_highlight": {
      "visibility": "visible",
      "color": "rgba(255,255,255,0.1)"
    },
    "mx_map_mask": {
      "visibility": "visible",
      "color": "rgba(153,153,153,0.4)"
    },
    "mx_map_text_place": {
      "visibility": "visible",
      "color": "rgba(47,47,47,0.8)"
    },
    "mx_map_text_place_outline": {
      "visibility": "visible",
      "color": "rgba(48,48,48,0)"
    },
    "mx_map_text_road": {
      "visibility": "none",
      "color": "rgba(121,121,121,0.5)"
    },
    "mx_map_text_road_outline": {
      "visibility": "none",
      "color": "rgba(220,220,220,0.2)"
    },
    "mx_map_text_water": {
      "visibility": "visible",
      "color": "rgba(37,78,101,0.9)"
    },
    "mx_map_text_water_outline": {
      "visibility": "visible",
      "color": "rgba(46,60,71,0.1)"
    },
    "mx_map_water": {
      "visibility": "visible",
      "color": "rgb(189,209,227)"
    },
    "mx_map_bathymetry_high": {
      "visibility": "visible",
      "color": "rgba(109,156,190,0.5)"
    },
    "mx_map_bathymetry_low": {
      "visibility": "visible",
      "color": "rgba(11,16,19,0.5)"
    },
    "mx_map_road": {
      "visibility": "none",
      "color": "rgb(255,255,255)"
    },
    "mx_map_road_border": {
      "visibility": "none",
      "color": "rgba(220,220,220,0.5)"
    },
    "mx_map_building": {
      "visibility": "visible",
      "color": "rgba(220,220,220,0.5)"
    },
    "mx_map_boundary_un_1": {
      "visibility": "visible",
      "color": "rgba(38,38,38,0.3)"
    },
    "mx_map_boundary_un_2": {
      "visibility": "visible",
      "color": "rgba(38,38,38,0.3)"
    },
    "mx_map_boundary_un_3": {
      "visibility": "visible",
      "color": "rgba(38,38,38,0.3)"
    },
    "mx_map_boundary_un_4": {
      "visibility": "visible",
      "color": "rgba(38,38,38,0.3)"
    },
    "mx_map_boundary_un_8": {
      "visibility": "visible",
      "color": "rgba(38,38,38,0.3)"
    },
    "mx_map_boundary_un_9": {
      "visibility": "visible",
      "color": "rgba(38,38,38,0.3)"
    },
    "mx_map_boundary_un_6": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    }
  }
}

=== unep-grid/mapx/app/src/js/theme/themes/classic_dark.json
{
  "id": "classic_dark",
  "description": {
    "en": "Dark gray theme."
  },
  "author": "F.Moser",
  "mode": "dark",
  "sound": "switch-off",
  "colors": {
    "mx_ui_text": {
      "visibility": "visible",
      "color": "rgb(235,235,235)",
      "font": "Noto Sans"
    },
    "mx_ui_link": {
      "visibility": "visible",
      "color": "rgb(17,176,248)"
    },
    "mx_ui_input_accent": {
      "visibility": "visible",
      "color": "rgb(17,176,248)"
    },
    "mx_ui_text_faded": {
      "visibility": "visible",
      "color": "rgb(192,192,192)"
    },
    "mx_ui_hidden": {
      "visibility": "visible",
      "color": "rgba(0,84,147,0)"
    },
    "mx_ui_border": {
      "visibility": "visible",
      "color": "rgba(255,255,255,0.1)"
    },
    "mx_ui_background": {
      "visibility": "visible",
      "color": "rgb(66,66,66)"
    },
    "mx_ui_background_accent": {
      "visibility": "visible",
      "color": "rgb(70,70,70)"
    },
    "mx_ui_background_faded": {
      "visibility": "visible",
      "color": "rgb(51,51,51)"
    },
    "mx_ui_background_contrast": {
      "visibility": "visible",
      "color": "rgb(58,58,58)"
    },
    "mx_ui_background_transparent": {
      "visibility": "visible",
      "color": "rgba(66,66,66,0.5)"
    },
    "mx_ui_shadow": {
      "visibility": "visible",
      "color": "rgba(28,28,28,0.3)"
    },
    "mx_map_background": {
      "visibility": "visible",
      "color": "rgb(48,48,48)"
    },
    "mx_map_feature_highlight": {
      "visibility": "visible",
      "color": "rgb(0,255,0)"
    },
    "mx_map_hillshade_shadow": {
      "visibility": "visible",
      "color": "rgba(0,0,0,0.1)"
    },
    "mx_map_hillshade_highlight": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.2)"
    },
    "mx_map_mask": {
      "visibility": "visible",
      "color": "rgba(0,0,0,0.2)"
    },
    "mx_map_text_place": {
      "visibility": "visible",
      "color": "rgba(186,186,186,0.9)",
      "font": "Noto Sans Regular"
    },
    "mx_map_text_road": {
      "visibility": "visible",
      "color": "rgb(164,164,164)",
      "font": "Noto Sans Medium"
    },
    "mx_map_text_water": {
      "visibility": "visible",
      "color": "rgba(56,56,56,0.9)",
      "font": "Libre Baskerville Italic"
    },
    "mx_map_text_water_outline": {
      "visibility": "visible",
      "color": "rgba(46,60,71,0.1)"
    },
    "mx_map_water": {
      "visibility": "visible",
      "color": "rgb(143,143,143)"
    },
    "mx_map_bathymetry_high": {
      "visibility": "visible",
      "color": "rgba(135,135,135,0.87)"
    },
    "mx_map_bathymetry_low": {
      "visibility": "visible",
      "color": "rgba(23,22,22,0.91)"
    },
    "mx_map_bathymetry_lines": {
      "visibility": "none",
      "color": "rgb(255,255,255)"
    },
    "mx_map_road": {
      "visibility": "visible",
      "color": "rgb(5,5,5)"
    },
    "mx_map_road_border": {
      "visibility": "visible",
      "color": "rgb(84,84,84)"
    },
    "mx_map_building": {
      "visibility": "visible",
      "color": "rgba(64,64,64,0.76)"
    },
    "mx_map_boundary_un_1": {
      "visibility": "visible",
      "color": "rgb(121,121,121)"
    },
    "mx_map_boundary_un_2": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    },
    "mx_map_boundary_un_3": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    },
    "mx_map_boundary_un_4": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    },
    "mx_map_boundary_un_8": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    },
    "mx_map_boundary_un_9": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    },
    "mx_map_boundary_un_6": {
      "visibility": "visible",
      "color": "rgba(121,121,121,0.6)"
    },
    "mx_map_text_land_outline": {
      "visibility": "visible",
      "color": "rgba(48,48,48,0.24)"
    },
    "mx_map_text_bathymetry_outline": {
      "visibility": "none",
      "color": "rgba(255,255,255,0.9)"
    },
    "mx_map_text_bathymetry": {
      "visibility": "none",
      "color": "rgba(0,71,102,0.9)",
      "font": "Varela Round Regular"
    },
    "mx_map_text_country_0_0": {
      "visibility": "visible",
      "color": "rgb(247,247,247)",
      "font": "Noto Sans Medium Italic"
    },
    "mx_map_text_country_0_1": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Regular"
    },
    "mx_map_text_country_0_2": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Italic"
    },
    "mx_map_text_country_0_3": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Regular"
    },
    "mx_map_text_country_0_4": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Regular"
    },
    "mx_map_text_country_0_5": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Italic"
    },
    "mx_map_text_country_0_99": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Regular"
    },
    "mx_map_text_country_1_1": {
      "visibility": "visible",
      "color": "rgb(255,255,255)",
      "font": "Noto Sans Italic"
    }
  }
}
